#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org
# ABBA DIR-320 2020

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh

detect_by_model() {
	local model="$1"
	local boardtype="$2"
	local boardnum="$3"

	case "$model" in

	"D-Link DIR-320")
		ucidef_add_switch "switch0" \
			"0:wan" "1:lan" "2:lan" "3:lan" "4:lan" "5@eth0"
		;;
	*)
		detect_by_boardtype "$boardtype" "$boardnum"
		;;
	esac
}


## model="$(sed -ne 's/^machine[ \t]*: //p' /proc/cpuinfo)"
model="D-Link DIR-320"

boardtype="$(nvram get boardtype)"
boardnum="$(nvram get boardnum)"

board_config_update

ucidef_set_board_id "$boardtype${boardnum:+:$boardnum}"
ucidef_set_model_name "$model"

detect_by_model "$model" "$boardtype" "$boardnum"

board_config_flush
